# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MVVM With Alamofire' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MVVM With Alamofire


 pod 'Alamofire' 

  target 'MVVM With AlamofireTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVVM With AlamofireUITests' do
    # Pods for testing
  end

end
